import { WorkflowTemplate, Contract, ContractTemplate, DepartmentStats, NodeEfficiency, AmountDistribution, User } from '@/types';
import { generateContractCode } from './helpers';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();
const daysLater = (d: number) => new Date(now.getTime() + d * 24 * 60 * 60 * 1000).toISOString();

export const mockCurrentUser: User = {
  id: 'u5',
  name: '陈剑锋',
  role: 'approver',
  roleName: '法务审核员',
  department: '法务部',
  avatar: 'CJ',
};

export const mockWorkflows: WorkflowTemplate[] = [
  {
    id: 'wf1',
    name: '标准合同审批流程',
    description: '适用于金额100万以下的常规合同审批，涵盖起草、法务、财务、盖章、归档全流程',
    enabled: true,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(15),
    nodes: [
      { id: 'n1', type: 'start', name: '开始', x: 80, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [] },
      { id: 'n2', type: 'draft', name: '合同起草', x: 240, y: 200, assigneeType: 'supervisor', assignees: [], timeLimit: 2, timeUnit: 'day', requiredMaterials: ['合同草案', '立项说明'] },
      { id: 'n3', type: 'legal_review', name: '法务审核', x: 400, y: 200, assigneeType: 'role', assignees: ['法务部'], timeLimit: 2, timeUnit: 'day', requiredMaterials: ['完整合同文本', '相关附件'] },
      { id: 'n4', type: 'financial_review', name: '财务复核', x: 560, y: 200, assigneeType: 'role', assignees: ['财务部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['预算说明', '付款计划'] },
      { id: 'n5', type: 'stamp', name: '盖章用印', x: 720, y: 200, assigneeType: 'role', assignees: ['行政管理部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['最终合同文本', '审批流程表'] },
      { id: 'n6', type: 'archive', name: '合同归档', x: 880, y: 200, assigneeType: 'role', assignees: ['法务部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['盖章合同原件', '电子扫描件'] },
      { id: 'n7', type: 'end', name: '结束', x: 1040, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [] },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
    ],
  },
  {
    id: 'wf2',
    name: '大额合同审批流程',
    description: '适用于金额100万以上的重大合同，增加业务部门确认和多级审批环节',
    enabled: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
    nodes: [
      { id: 'm1', type: 'start', name: '开始', x: 60, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [] },
      { id: 'm2', type: 'draft', name: '合同起草', x: 200, y: 200, assigneeType: 'supervisor', assignees: [], timeLimit: 3, timeUnit: 'day', requiredMaterials: ['合同草案', '立项审批', '可行性报告'] },
      { id: 'm3', type: 'business_confirm', name: '业务确认', x: 340, y: 200, assigneeType: 'user', assignees: ['u3'], timeLimit: 2, timeUnit: 'day', requiredMaterials: ['业务方案说明'] },
      { id: 'm4', type: 'condition', name: '金额判断', x: 480, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [], conditionExpression: 'amount > 5000000' },
      { id: 'm5', type: 'legal_review', name: '法务初审', x: 620, y: 120, assigneeType: 'role', assignees: ['法务部'], timeLimit: 3, timeUnit: 'day', requiredMaterials: ['风险评估报告'] },
      { id: 'm6', type: 'legal_review', name: '法务复审', x: 620, y: 280, assigneeType: 'user', assignees: ['u8'], timeLimit: 3, timeUnit: 'day', requiredMaterials: ['初审意见', '完整合同'] },
      { id: 'm7', type: 'financial_review', name: '财务复核', x: 780, y: 200, assigneeType: 'role', assignees: ['财务部'], timeLimit: 2, timeUnit: 'day', requiredMaterials: ['资金来源证明'] },
      { id: 'm8', type: 'stamp', name: '盖章用印', x: 920, y: 200, assigneeType: 'role', assignees: ['行政管理部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['全部审批文件'] },
      { id: 'm9', type: 'archive', name: '合同归档', x: 1060, y: 200, assigneeType: 'role', assignees: ['法务部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['原件3份+扫描件'] },
      { id: 'm10', type: 'end', name: '结束', x: 1200, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [] },
    ],
    connections: [
      { id: 'mc1', from: 'm1', to: 'm2' },
      { id: 'mc2', from: 'm2', to: 'm3' },
      { id: 'mc3', from: 'm3', to: 'm4' },
      { id: 'mc4', from: 'm4', to: 'm5', label: '≤500万', condition: 'amount <= 5000000' },
      { id: 'mc5', from: 'm4', to: 'm6', label: '>500万', condition: 'amount > 5000000' },
      { id: 'mc6', from: 'm5', to: 'm7' },
      { id: 'mc7', from: 'm6', to: 'm7' },
      { id: 'mc8', from: 'm7', to: 'm8' },
      { id: 'mc9', from: 'm8', to: 'm9' },
      { id: 'mc10', from: 'm9', to: 'm10' },
    ],
  },
  {
    id: 'wf3',
    name: '简易合同流程',
    description: '适用于10万以下的常规类合同，简化审批环节',
    enabled: false,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    nodes: [
      { id: 's1', type: 'start', name: '开始', x: 100, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [] },
      { id: 's2', type: 'draft', name: '合同起草', x: 260, y: 200, assigneeType: 'supervisor', assignees: [], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['合同文本'] },
      { id: 's3', type: 'legal_review', name: '法务审核', x: 420, y: 200, assigneeType: 'role', assignees: ['法务部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: [] },
      { id: 's4', type: 'stamp', name: '盖章', x: 580, y: 200, assigneeType: 'role', assignees: ['行政管理部'], timeLimit: 4, timeUnit: 'hour', requiredMaterials: ['合同原件'] },
      { id: 's5', type: 'archive', name: '归档', x: 740, y: 200, assigneeType: 'role', assignees: ['法务部'], timeLimit: 1, timeUnit: 'day', requiredMaterials: ['扫描件'] },
      { id: 's6', type: 'end', name: '结束', x: 900, y: 200, assigneeType: 'auto', assignees: [], timeLimit: 0, timeUnit: 'hour', requiredMaterials: [] },
    ],
    connections: [
      { id: 'sc1', from: 's1', to: 's2' },
      { id: 'sc2', from: 's2', to: 's3' },
      { id: 'sc3', from: 's3', to: 's4' },
      { id: 'sc4', from: 's4', to: 's5' },
      { id: 'sc5', from: 's5', to: 's6' },
    ],
  },
];

export const mockContracts: Contract[] = [
  {
    id: 'ct1',
    code: generateContractCode('purchase'),
    name: '办公设备年度采购框架协议',
    type: 'purchase',
    amount: 856000,
    status: 'pending',
    priority: 'high',
    workflowId: 'wf1',
    currentNodeId: 'n3',
    applicantId: 'u2',
    applicantName: '李思琪',
    department: '采购供应部',
    createTime: daysAgo(3),
    expectedArchiveTime: daysLater(5),
    attachments: [
      { id: 'a1', name: '采购框架协议草案.docx', size: 245000, uploadTime: daysAgo(3), uploader: '李思琪', fileType: 'docx' },
      { id: 'a2', name: '供应商报价单.xlsx', size: 89000, uploadTime: daysAgo(3), uploader: '李思琪', fileType: 'xlsx' },
      { id: 'a3', name: '立项审批表.pdf', size: 1024000, uploadTime: daysAgo(2), uploader: '李思琪', fileType: 'pdf' },
    ],
    approvalHistory: [
      { nodeId: 'n2', nodeName: '合同起草', approverId: 'u2', approverName: '李思琪', action: 'approve', opinion: '已完成合同草案，采购设备清单与报价已核对无误，请法务审核。', time: daysAgo(3) },
    ],
  },
  {
    id: 'ct2',
    code: generateContractCode('sales'),
    name: '华东区域销售合作协议',
    type: 'sales',
    amount: 3200000,
    status: 'pending',
    priority: 'urgent',
    workflowId: 'wf2',
    currentNodeId: 'm6',
    applicantId: 'u1',
    applicantName: '张明远',
    department: '市场销售部',
    createTime: daysAgo(7),
    expectedArchiveTime: daysLater(2),
    attachments: [
      { id: 'b1', name: '销售合作协议终稿.docx', size: 312000, uploadTime: daysAgo(7), uploader: '张明远', fileType: 'docx' },
      { id: 'b2', name: '合作方资质文件.zip', size: 5400000, uploadTime: daysAgo(7), uploader: '张明远', fileType: 'zip' },
    ],
    approvalHistory: [
      { nodeId: 'm2', nodeName: '合同起草', approverId: 'u1', approverName: '张明远', action: 'approve', opinion: '合同草案已完成，合作条款经双方初步沟通确认。', time: daysAgo(7) },
      { nodeId: 'm3', nodeName: '业务确认', approverId: 'u3', approverName: '王建国', action: 'approve', opinion: '业务方案可行，符合年度销售目标，同意推进。', time: daysAgo(6) },
      { nodeId: 'm5', nodeName: '法务初审', approverId: 'u5', approverName: '陈剑锋', action: 'approve', opinion: '合同条款基本合规，建议完善违约责任条款第8.3条，已在文本中标注。', time: daysAgo(4) },
    ],
  },
  {
    id: 'ct3',
    code: generateContractCode('service'),
    name: '信息系统运维服务合同',
    type: 'service',
    amount: 480000,
    status: 'pending',
    priority: 'medium',
    workflowId: 'wf1',
    currentNodeId: 'n4',
    applicantId: 'u1',
    applicantName: '张明远',
    department: '市场销售部',
    createTime: daysAgo(5),
    expectedArchiveTime: daysLater(3),
    attachments: [
      { id: 'c1', name: '运维服务合同.docx', size: 198000, uploadTime: daysAgo(5), uploader: '张明远', fileType: 'docx' },
      { id: 'c2', name: 'SLA服务等级协议.pdf', size: 456000, uploadTime: daysAgo(5), uploader: '张明远', fileType: 'pdf' },
    ],
    approvalHistory: [
      { nodeId: 'n2', nodeName: '合同起草', approverId: 'u1', approverName: '张明远', action: 'approve', opinion: '合同及SLA协议已完成，服务范围与报价确认。', time: daysAgo(5) },
      { nodeId: 'n3', nodeName: '法务审核', approverId: 'u5', approverName: '陈剑锋', action: 'approve', opinion: '条款合规，服务期限和终止条款已核对。', time: daysAgo(3) },
    ],
  },
  {
    id: 'ct4',
    code: generateContractCode('labor'),
    name: '高级技术专家聘用协议',
    type: 'labor',
    amount: 720000,
    status: 'approved',
    priority: 'high',
    workflowId: 'wf1',
    currentNodeId: 'n5',
    applicantId: 'u2',
    applicantName: '李思琪',
    department: '人力资源部',
    createTime: daysAgo(10),
    expectedArchiveTime: daysLater(1),
    attachments: [
      { id: 'd1', name: '聘用协议.docx', size: 156000, uploadTime: daysAgo(10), uploader: '李思琪', fileType: 'docx' },
    ],
    approvalHistory: [
      { nodeId: 'n2', nodeName: '合同起草', approverId: 'u2', approverName: '李思琪', action: 'approve', opinion: '聘用协议已按薪酬委员会决议拟定。', time: daysAgo(10) },
      { nodeId: 'n3', nodeName: '法务审核', approverId: 'u5', approverName: '陈剑锋', action: 'approve', opinion: '竞业限制和保密条款完善。', time: daysAgo(8) },
      { nodeId: 'n4', nodeName: '财务复核', approverId: 'u6', approverName: '周雪梅', action: 'approve', opinion: '薪酬预算已确认，符合年度人力成本规划。', time: daysAgo(6) },
    ],
  },
  {
    id: 'ct5',
    code: generateContractCode('purchase'),
    name: '原材料长期供货合同',
    type: 'purchase',
    amount: 6800000,
    status: 'pending',
    priority: 'urgent',
    workflowId: 'wf2',
    currentNodeId: 'm7',
    applicantId: 'u2',
    applicantName: '李思琪',
    department: '采购供应部',
    createTime: daysAgo(14),
    expectedArchiveTime: daysLater(7),
    attachments: [
      { id: 'e1', name: '供货合同主协议.docx', size: 425000, uploadTime: daysAgo(14), uploader: '李思琪', fileType: 'docx' },
      { id: 'e2', name: '价格清单附件.xlsx', size: 67000, uploadTime: daysAgo(14), uploader: '李思琪', fileType: 'xlsx' },
    ],
    approvalHistory: [
      { nodeId: 'm2', nodeName: '合同起草', approverId: 'u2', approverName: '李思琪', action: 'approve', opinion: '已按年度采购计划完成框架协议草案。', time: daysAgo(14) },
      { nodeId: 'm3', nodeName: '业务确认', approverId: 'u4', approverName: '赵敏', action: 'approve', opinion: '生产需求已确认，供货周期满足排产计划。', time: daysAgo(12) },
      { nodeId: 'm6', nodeName: '法务复审', approverId: 'u8', approverName: '孙文涛', action: 'approve', opinion: '重大条款已审核，价格保护和违约条款约定清晰。', time: daysAgo(7) },
    ],
  },
  {
    id: 'ct6',
    code: generateContractCode('sales'),
    name: '年度渠道分销合同',
    type: 'sales',
    amount: 12500000,
    status: 'archived',
    priority: 'high',
    workflowId: 'wf2',
    currentNodeId: 'm10',
    applicantId: 'u1',
    applicantName: '张明远',
    department: '市场销售部',
    createTime: daysAgo(45),
    expectedArchiveTime: daysAgo(30),
    actualArchiveTime: daysAgo(28),
    attachments: [
      { id: 'f1', name: '分销合同.pdf', size: 892000, uploadTime: daysAgo(45), uploader: '张明远', fileType: 'pdf' },
    ],
    approvalHistory: [
      { nodeId: 'm2', nodeName: '合同起草', approverId: 'u1', approverName: '张明远', action: 'approve', opinion: '', time: daysAgo(45) },
      { nodeId: 'm3', nodeName: '业务确认', approverId: 'u3', approverName: '王建国', action: 'approve', opinion: '渠道策略符合年度规划', time: daysAgo(43) },
      { nodeId: 'm6', nodeName: '法务复审', approverId: 'u8', approverName: '孙文涛', action: 'approve', opinion: '条款完善', time: daysAgo(40) },
      { nodeId: 'm7', nodeName: '财务复核', approverId: 'u6', approverName: '周雪梅', action: 'approve', opinion: '返利条款核算无误', time: daysAgo(37) },
      { nodeId: 'm8', nodeName: '盖章用印', approverId: 'u7', approverName: '刘德华', action: 'approve', opinion: '用印完成', time: daysAgo(33) },
      { nodeId: 'm9', nodeName: '合同归档', approverId: 'u5', approverName: '陈剑锋', action: 'approve', opinion: '原件3份已归档', time: daysAgo(28) },
    ],
  },
  {
    id: 'ct7',
    code: generateContractCode('service'),
    name: '办公楼清洁外包合同',
    type: 'service',
    amount: 96000,
    status: 'archived',
    priority: 'low',
    workflowId: 'wf1',
    currentNodeId: 'n7',
    applicantId: 'u2',
    applicantName: '李思琪',
    department: '行政管理部',
    createTime: daysAgo(60),
    expectedArchiveTime: daysAgo(50),
    actualArchiveTime: daysAgo(49),
    attachments: [
      { id: 'g1', name: '清洁服务合同.pdf', size: 234000, uploadTime: daysAgo(60), uploader: '李思琪', fileType: 'pdf' },
    ],
    approvalHistory: [
      { nodeId: 'n2', nodeName: '合同起草', approverId: 'u2', approverName: '李思琪', action: 'approve', opinion: '', time: daysAgo(60) },
      { nodeId: 'n3', nodeName: '法务审核', approverId: 'u5', approverName: '陈剑锋', action: 'approve', opinion: '', time: daysAgo(58) },
      { nodeId: 'n4', nodeName: '财务复核', approverId: 'u6', approverName: '周雪梅', action: 'approve', opinion: '', time: daysAgo(55) },
      { nodeId: 'n5', nodeName: '盖章用印', approverId: 'u7', approverName: '刘德华', action: 'approve', opinion: '', time: daysAgo(52) },
      { nodeId: 'n6', nodeName: '合同归档', approverId: 'u5', approverName: '陈剑锋', action: 'approve', opinion: '', time: daysAgo(49) },
    ],
  },
  {
    id: 'ct8',
    code: generateContractCode('purchase'),
    name: 'CRM软件采购合同',
    type: 'purchase',
    amount: 368000,
    status: 'rejected',
    priority: 'medium',
    workflowId: 'wf1',
    currentNodeId: 'n3',
    applicantId: 'u1',
    applicantName: '张明远',
    department: '技术研发部',
    createTime: daysAgo(8),
    expectedArchiveTime: daysAgo(2),
    attachments: [
      { id: 'h1', name: '软件采购合同草案.docx', size: 178000, uploadTime: daysAgo(8), uploader: '张明远', fileType: 'docx' },
    ],
    approvalHistory: [
      { nodeId: 'n2', nodeName: '合同起草', approverId: 'u1', approverName: '张明远', action: 'approve', opinion: '已完成采购需求整理和供应商选型。', time: daysAgo(8) },
      { nodeId: 'n3', nodeName: '法务审核', approverId: 'u5', approverName: '陈剑锋', action: 'reject', opinion: '第5.2条数据安全条款不完善，需补充数据脱敏和隐私合规约定；第7条知识产权归属需重新约定。请修改后重新提交。', time: daysAgo(5) },
    ],
  },
];

export const mockTemplates: ContractTemplate[] = [
  { id: 't1', name: '货物采购合同标准模板', type: 'purchase', version: 'v3.2', description: '适用于生产原材料、办公设备等货物类采购，包含交付、验收、质保等标准条款', fileName: '货物采购合同标准模板_v3.2.docx', fileSize: 245000, usageCount: 156, lastUpdated: daysAgo(8), enabled: true },
  { id: 't2', name: '产品销售合同标准模板', type: 'sales', version: 'v4.1', description: '适用于各类产品销售，含分期付款、质保服务、违约责任等完整条款', fileName: '产品销售合同标准模板_v4.1.docx', fileSize: 278000, usageCount: 203, lastUpdated: daysAgo(12), enabled: true },
  { id: 't3', name: '技术服务合同模板', type: 'service', version: 'v2.5', description: '适用于技术开发、运维服务、咨询服务等服务类合同', fileName: '技术服务合同模板_v2.5.docx', fileSize: 198000, usageCount: 87, lastUpdated: daysAgo(5), enabled: true },
  { id: 't4', name: '劳务聘用协议模板', type: 'labor', version: 'v5.0', description: '适用于全职员工劳动合同签署，含薪酬、社保、保密、竞业等条款', fileName: '劳务聘用协议模板_v5.0.docx', fileSize: 156000, usageCount: 312, lastUpdated: daysAgo(3), enabled: true },
  { id: 't5', name: '大额采购框架协议', type: 'purchase', version: 'v1.3', description: '适用于年度/半年度大额采购框架协议，约定年度价格和供货条款', fileName: '大额采购框架协议_v1.3.docx', fileSize: 312000, usageCount: 42, lastUpdated: daysAgo(20), enabled: true },
  { id: 't6', name: '渠道经销合作协议', type: 'sales', version: 'v2.0', description: '适用于代理商、分销商渠道合作，含区域保护、返利政策等', fileName: '渠道经销合作协议_v2.0.docx', fileSize: 289000, usageCount: 58, lastUpdated: daysAgo(15), enabled: true },
  { id: 't7', name: '软件开发外包合同', type: 'service', version: 'v1.8', description: '适用于软件定制开发外包，含需求规格、里程碑、验收标准等', fileName: '软件开发外包合同_v1.8.docx', fileSize: 267000, usageCount: 35, lastUpdated: daysAgo(10), enabled: true },
  { id: 't8', name: '保密协议（NDA）模板', type: 'other', version: 'v2.2', description: '适用于项目合作前的双向保密协议签署', fileName: '保密协议模板_v2.2.docx', fileSize: 98000, usageCount: 267, lastUpdated: daysAgo(2), enabled: true },
];

export const mockDepartmentStats: DepartmentStats[] = [
  { department: '市场销售部', totalContracts: 89, avgDuration: 6.2, completedCount: 76, rejectedCount: 8 },
  { department: '采购供应部', totalContracts: 72, avgDuration: 7.5, completedCount: 61, rejectedCount: 6 },
  { department: '技术研发部', totalContracts: 34, avgDuration: 8.1, completedCount: 28, rejectedCount: 4 },
  { department: '人力资源部', totalContracts: 156, avgDuration: 4.8, completedCount: 148, rejectedCount: 3 },
  { department: '财务部', totalContracts: 18, avgDuration: 5.5, completedCount: 16, rejectedCount: 1 },
  { department: '行政管理部', totalContracts: 45, avgDuration: 5.2, completedCount: 42, rejectedCount: 2 },
];

export const mockNodeEfficiency: NodeEfficiency[] = [
  { nodeName: '合同起草', avgDuration: 1.8, totalCount: 520, timeoutCount: 18, rejectionRate: 2.5 },
  { nodeName: '业务确认', avgDuration: 1.5, totalCount: 210, timeoutCount: 12, rejectionRate: 3.8 },
  { nodeName: '法务审核', avgDuration: 2.2, totalCount: 520, timeoutCount: 35, rejectionRate: 8.2 },
  { nodeName: '财务复核', avgDuration: 1.2, totalCount: 480, timeoutCount: 15, rejectionRate: 1.8 },
  { nodeName: '盖章用印', avgDuration: 0.8, totalCount: 450, timeoutCount: 8, rejectionRate: 0.5 },
  { nodeName: '合同归档', avgDuration: 0.6, totalCount: 445, timeoutCount: 5, rejectionRate: 0.2 },
];

export const mockAmountDistribution: AmountDistribution[] = [
  { range: '10万以下', count: 186, totalAmount: 9850000 },
  { range: '10-50万', count: 142, totalAmount: 42600000 },
  { range: '50-100万', count: 87, totalAmount: 65250000 },
  { range: '100-500万', count: 65, totalAmount: 178750000 },
  { range: '500万以上', count: 28, totalAmount: 336000000 },
];
